site_name: Cyber Range Kyoushi Dataset
site_url: "https://ait-aecid.github.io/kyoushi-dataset"

site_description: IDS Dataset processing and labeling tool.
strict: true

theme:
  name: 'material'
  logo: images/cr_icon.svg
  favicon: images/favicon.ico
  palette:
    scheme: ait

extra_css:
  - stylesheets/extra.css
  - stylesheets/jquery.fancybox.min.css

# Extra javascript
extra_javascript:
  - js/jquery-3.5.1.min.js
  - js/jquery.fancybox.min.js

repo_name: kyoushi-dataset
repo_url: https://github.com/ait-aecid/kyoushi-dataset
# need to set manually since we use a private gitlab instance
edit_uri: edit/main/docs/

nav:
- Overview: index.md
- Getting Started:
    - Intro: getting_started/intro.md
    - Prepare Dataset: getting_started/prepare.md
    - Process Dataset: getting_started/process.md
    - Label Dataset: getting_started/label.md
    - Sample Labels: getting_started/sample.md
- Dataset Processors: processors.md
- Labeling Rules: rules.md
- CLI Reference: cli.md
- Code Reference:
    - Config: reference/config.md
    - Elasticsearch: reference/elasticsearch.md
    - Labels: reference/labels.md
    - Parser: reference/parser.md
    - PCAP Utilities: reference/pcap.md
    - Processors: reference/processors.md
    - Sampling: reference/sample.md
    - Templates: reference/templates.md
    - Utility Functions: reference/utils.md
- Contributing: contributing.md
- License: license.md

markdown_extensions:
    - admonition
    - attr_list
    - mkdocs-click
    - markdown_include.include
    - pymdownx.emoji
    - pymdownx.magiclink
    - pymdownx.highlight
    - pymdownx.inlinehilite
    - pymdownx.keys
    - pymdownx.tabbed
    - pymdownx.tasklist
    - pymdownx.extra
    - pymdownx.details
    - toc:
        permalink: true
        toc_depth: 3



plugins:
- search
- exclude:
    glob:
    - _build/*
    - build/*
- mkdocstrings:
    default_handler: python
    handlers:
      python:
        selection:
            new_path_syntax: yes
            filters:
              - "!^_[^_]"
              - "!^__class__"
        rendering:
          show_source: true
    watch:
      - src/cr_kyoushi/dataset
      - README.md
      - CONTRIBUTING.md
- macros:
