hosts:
  webserver:
    - path: apache2/*access*.log*
      type: apache_access
    - path: apache2/*error*.log*
      type: apache_error

  vpn:
    - path: openvpn.log*
      type: openvpn

  intranet_server:
    - path: apache2/*access*.log*
      type: apache_access
    - path: apache2/*error*.log*
      type: apache_error
      add_field:
        "[@metadata][kyoushi][httpd_dirs]": [
                "/var/www/intranet.example.cyberrange.at", "",
                "/usr/share/javascript", "/javascript"
          ]

  cloud_share:
    - path: apache2/*access*.log*
      type: apache_access
    - path: apache2/*error*.log*
      type: apache_error

  attacker_0:
    - path: ait.aecid.attacker.wpdiscuz/sm.log*
      type: kyoushi
      codec: json
      # attack output lines can be **very** long
      file_chunk_size: 200000000
      add_field:
        "[@metadata][kyoushi][sm]": "attacker"
    - path: ait.aecid.attacker.wpdiscuz/traffic.json
      type: pcap
      file_chunk_size: 200000000
      codec: json

groups:
  employee:
    - path: sm.log*
      type: kyoushi
      codec: json
      # some of the ssh output logs are very long
      file_chunk_size: 320000
      add_field:
        "[@metadata][kyoushi][sm]": "user"

  ext_user:
    - path: sm.log*
      type: kyoushi
      codec: json
      add_field:
        "[@metadata][kyoushi][sm]": "user"

  servers:
    - path: audit/audit.log*
      type: audit
      add_field:
        "[@metadata][pipeline]": "auditd-logs"
    - path: auth.log*
      type: auth
    - path: syslog*
      type: syslog

  mailserver:
    - path: horde/*access.log*
      type: apache_access
    - path: horde/*error.log*
      type: apache_error
    - path: mail.err*
      type: syslog
    - path: mail.info*
      type: syslog
    - path: mail.log*
      type: syslog
    - path: mail.warn*
      type: syslog

  dnsservers:
    - path: dnsmasq.log*
      type: dnsmasq
