name: Test and Build

on:
  pull_request:
    branches:
      - main

jobs:
  test3.7:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - uses: Gr1N/setup-poetry@v4
      - uses: actions/cache@v2
        with:
          path: ~/.cache/pypoetry/virtualenvs
          key: ${{ runner.os }}-poetry-${{ hashFiles('poetry.lock') }}
      - run: poetry --version
      - run: poetry config virtualenvs.in-project true 
      - run: poetry install -v
      - run: make check-black
      - run: make check-flake8
      - run: make check-isort
      - run: make check-mypy
      - run: make check-safety
      - run: make test-junit
      - uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - run: make test-junit

